name: reusable

on:
  workflow_call: 
    inputs:
      env:
        required: false
        type: string
        default: ""

jobs:
  print-env-vars:
    runs-on: ubuntu-latest
    steps:
    - name: "print envs vars"
      run:
        env


