name: reusable

on:
  workflow_call: 
    inputs:
      FOO:
        required: true
        type: string
        

jobs:
  print-env-vars:
    runs-on: ubuntu-latest
    steps:
    - name: "print envs vars"
      env:
        FOO:  ${{ inputs.FOO }}
      run:
        env


