name: reusable

on:
  workflow_call: 
    inputs:
      FOO:
        required: true
        type: string
      BAR:
        required: false
        type: string
        default: null

jobs:
  print-env-vars:
    runs-on: ubuntu-latest
    steps:
    - name: "print envs vars"
      env:
        FOO: ${{ inputs.FOO }}
        BAR: ${{ inputs.BAR }}
      run:
        env


